version: "2"
services:
  disk:
    container_name: disk
    image: debian:jessie
    volumes:
      - /etc/nginx:/etc/nginx
      - /etc/nginx:/usr/local/openresty/nginx/conf
      - /var/log/nginx:/var/log/nginx
      - /var/log/letsencrypt:/var/log/letsencrypt 
      - /var/log/php-fpm:/var/log/php-fpm
      - /var/log/nginx:/usr/local/openresty/nginx/logs
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/run2:/var/run
      - /var/run2/nginx-cache/ngx_pagespeed:/var/cache/ngx_pagespeed 
      - /var/www:/var/www
      - ${HOME}:${HOME}
    networks:
      devkit:
          ipv4_address: 172.28.5.60
  php-fpm7:
    container_name: php7
    volumes_from:
      - disk
    volumes:
      - /etc/passwd:/etc/passwd
      - /etc/group:/etc/group
    build: 
      context: ./Dockerfiles
      dockerfile: dockerfile-php7
    networks:
      devkit:
          ipv4_address: 172.28.5.63
    extra_hosts:
      - "db:172.28.5.64"
  php-fpm6:
    container_name: php6
    volumes_from:
      - disk
    volumes:
      - /etc/passwd:/etc/passwd
      - /etc/group:/etc/group
    build:
      context: ./Dockerfiles
      dockerfile: dockerfile-php6
    networks:
      devkit:
          ipv4_address: 172.28.5.62
    extra_hosts:
      - "db:172.28.5.64"
  webserver:
    container_name: webserver
    volumes_from:
      - disk
    build:
      context: ./Dockerfiles
      dockerfile: dockerfile-nginx-module-pagespeed
    ports:
      - "80:80"
      - "443:443"
    networks:
      devkit:
          ipv4_address: 172.28.5.61
  mysql:
    container_name: mysql
    volumes_from:
      - disk
    build:
      context: ./Dockerfiles
      dockerfile: dockerfile-mysql
    volumes:
      - /var/lib/mysql:/var/lib/mysql
      - /var/log/mysql:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      devkit:
          ipv4_address: 172.28.5.64
  node:
    container_name: node
    volumes_from:
      - disk
    build:
      context: ./Dockerfiles
      dockerfile: dockerfile-node
    networks:
      devkit:
          ipv4_address: 172.28.5.65
networks:
  devkit:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.28.0.0/16
